package provider

import (
	"fmt"
	"os"
	"strconv"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
)

// minimalKeytabB64 is a hand-crafted minimal valid MIT Kerberos keytab
// (file format v5.2) containing a single rc4-hmac key for
// acctest@ACCTEST.LOCAL with an all-zero key. SCALE 25.10 validates the
// keytab structure at create time ("File does not contain any keytab
// entries"), so an opaque base64 blob is rejected. This blob parses
// successfully and is safe — the principal/realm/key are dummies and the
// keytab is never actually used for authentication during acc tests.
//
// Generated by hand from the keytab format spec:
// https://web.mit.edu/kerberos/krb5-1.12/doc/formats/keytab_file_format.html
const minimalKeytabB64 = "BQIAAAA3AAEADUFDQ1RFU1QuTE9DQUwAB2FjY3Rlc3QAAAABSZYC0gEAFwAQAAAAAAAAAAAAAAAAAAAAAA=="

// dummyKeytabB64 returns a valid base64-encoded minimal keytab payload.
// The argument is unused but retained so callers can pass a per-test label
// for documentation purposes.
func dummyKeytabB64(_ string) string {
	return minimalKeytabB64
}

// TestAccKerberosKeytabResource_basic creates a keytab entry with a dummy
// base64 payload. The `file` attribute is sensitive and may be re-encoded
// on round-trip, so it is excluded from ImportStateVerify.
func TestAccKerberosKeytabResource_basic(t *testing.T) {
	if os.Getenv("TF_ACC") == "" {
		t.Skip(skipMsg)
	}
	name := randomName("acctest-kt")
	payload := dummyKeytabB64("acctest-basic-payload")
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: fmt.Sprintf(`
resource "truenas_kerberos_keytab" "test" {
  name = %q
  file = %q
}
`, name, payload),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("truenas_kerberos_keytab.test", "name", name),
					resource.TestCheckResourceAttrSet("truenas_kerberos_keytab.test", "id"),
				),
			},
			{
				ResourceName:            "truenas_kerberos_keytab.test",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"file"},
			},
		},
	})
}

// TestAccKerberosKeytabResource_update renames the keytab entry in place.
func TestAccKerberosKeytabResource_update(t *testing.T) {
	if os.Getenv("TF_ACC") == "" {
		t.Skip(skipMsg)
	}
	name1 := randomName("acctest-kt-v1")
	name2 := randomName("acctest-kt-v2")
	payload := dummyKeytabB64("acctest-update-payload")
	cfg := func(n string) string {
		return fmt.Sprintf(`
resource "truenas_kerberos_keytab" "test" {
  name = %q
  file = %q
}
`, n, payload)
	}
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: cfg(name1),
				Check:  resource.TestCheckResourceAttr("truenas_kerberos_keytab.test", "name", name1),
			},
			{
				Config: cfg(name2),
				Check:  resource.TestCheckResourceAttr("truenas_kerberos_keytab.test", "name", name2),
			},
		},
	})
}

// TestAccKerberosKeytabResource_disappears deletes the keytab entry
// out-of-band and verifies the provider detects the drift.
func TestAccKerberosKeytabResource_disappears(t *testing.T) {
	if os.Getenv("TF_ACC") == "" {
		t.Skip(skipMsg)
	}
	name := randomName("acctest-kt-gone")
	payload := dummyKeytabB64("acctest-gone-payload")
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: fmt.Sprintf(`
resource "truenas_kerberos_keytab" "test" {
  name = %q
  file = %q
}
`, name, payload),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet("truenas_kerberos_keytab.test", "id"),
					func(s *terraform.State) error {
						rs, ok := s.RootModule().Resources["truenas_kerberos_keytab.test"]
						if !ok {
							return fmt.Errorf("truenas_kerberos_keytab.test not in state")
						}
						id, err := strconv.Atoi(rs.Primary.ID)
						if err != nil {
							return fmt.Errorf("parse id: %w", err)
						}
						c, err := testAccClient()
						if err != nil {
							return err
						}
						ctx, cancel := testAccCtx()
						defer cancel()
						return c.DeleteKerberosKeytab(ctx, id)
					},
				),
				ExpectNonEmptyPlan: true,
			},
		},
	})
}
